/// Übersetzte Ansagen für die Sprachausgabe (SAR-121).
///
/// Nur die **Stimme** spricht die gewählte Sprache – der Schülerschirm bleibt
/// deutsch mit Verkehrszeichen, so wie in der Prüfung. Deutsch steht hier
/// nicht: es spricht, was auf dem Schirm steht (`displayLabel`).
///
/// Anrede durchgehend informell, wie die deutschen Kacheln („Lass dir Zeit").
/// `test/speech_output_test.dart` prüft, dass jede Sprache jeden
/// Katalogeintrag kennt – eine neue Kachel ohne Übersetzung fällt dort auf,
/// nicht erst im Auto (sonst spräche sie dort deutsch).
library;

/// Sprachen, die der Fahrlehrer wählen kann.
enum VoiceLanguage {
  de('de', 'de-DE', 'Deutsch'),
  en('en', 'en-GB', 'English'),
  tr('tr', 'tr-TR', 'Türkçe'),
  ar('ar', 'ar-SA', 'العربية'),
  uk('uk', 'uk-UA', 'Українська'),
  ru('ru', 'ru-RU', 'Русский');

  /// Kurzcode auf der Leitung (`DriveCommand.voice`).
  final String code;

  /// Locale für die Sprachsynthese.
  final String locale;

  /// Name in der eigenen Sprache – so findet ihn auch, wer kein Deutsch liest.
  final String nativeName;

  const VoiceLanguage(this.code, this.locale, this.nativeName);

  /// `null` für leer (stumm) oder einen Code, den dieses Gerät nicht kennt.
  static VoiceLanguage? byCode(String code) {
    for (final l in values) {
      if (l.code == code) return l;
    }
    return null;
  }
}

/// Einleitung einer Abfrage („Zeige mir: …").
const Map<VoiceLanguage, String> kVoiceAsk = {
  VoiceLanguage.en: 'Show me',
  VoiceLanguage.tr: 'Bana göster',
  VoiceLanguage.ar: 'أرني',
  VoiceLanguage.uk: 'Покажи',
  VoiceLanguage.ru: 'Покажи',
};

/// „N. Straße links/rechts" – die einzige Ordnungszahl, die der Sender an ein
/// Kommando hängt (`kOrdinalNoun`). Die Ausfahrten sind eigene Kacheln.
String? voiceOrdinalTurn(VoiceLanguage lang, int ord, {required bool right}) {
  if (ord < 1 || ord > 9) return null;
  final i = ord - 1;
  return switch (lang) {
    VoiceLanguage.de => null,
    VoiceLanguage.en => '${_en[i]} street on the ${right ? 'right' : 'left'}',
    VoiceLanguage.tr => '${_tr[i]} sokaktan ${right ? 'sağa' : 'sola'}',
    VoiceLanguage.ar => 'الشارع ${_ar[i]} ${right ? 'يمينًا' : 'يسارًا'}',
    VoiceLanguage.uk => '${_uk[i]} вулиця ${right ? 'праворуч' : 'ліворуч'}',
    VoiceLanguage.ru => '${_ru[i]} улица ${right ? 'направо' : 'налево'}',
  };
}

const _en = [
  'First',
  'Second',
  'Third',
  'Fourth',
  'Fifth',
  'Sixth',
  'Seventh',
  'Eighth',
  'Ninth',
];
const _tr = [
  'Birinci',
  'İkinci',
  'Üçüncü',
  'Dördüncü',
  'Beşinci',
  'Altıncı',
  'Yedinci',
  'Sekizinci',
  'Dokuzuncu',
];
const _ar = [
  'الأول',
  'الثاني',
  'الثالث',
  'الرابع',
  'الخامس',
  'السادس',
  'السابع',
  'الثامن',
  'التاسع',
];
const _uk = [
  'Перша',
  'Друга',
  'Третя',
  'Четверта',
  'П’ята',
  'Шоста',
  'Сьома',
  'Восьма',
  'Дев’ята',
];
const _ru = [
  'Первая',
  'Вторая',
  'Третья',
  'Четвёртая',
  'Пятая',
  'Шестая',
  'Седьмая',
  'Восьмая',
  'Девятая',
];

/// Ansage je Sprache und Katalog-Key.
const Map<VoiceLanguage, Map<String, String>> kVoicePhrases = {
  VoiceLanguage.en: {
    // Richtung
    'links': 'Left',
    'rechts': 'Right',
    'geradeaus': 'Straight on',
    'abbiegen_links': 'Turn left',
    'abbiegen_rechts': 'Turn right',
    'einordnen_links': 'Get in the left lane',
    'einordnen': 'Get in lane',
    'einordnen_rechts': 'Get in the right lane',
    'kreisverkehr': 'Roundabout',
    'ampel': 'Traffic lights',
    'ausfahrt1': 'First exit',
    'ausfahrt2': 'Second exit',
    'ausfahrt3': 'Third exit',
    'folgen': 'Follow the road',
    'rueckwaerts': 'Reverse',
    // Tempo
    'langsamer': 'Slow down',
    'schneller': 'Speed up',
    'bremsen': 'Brake',
    'parken': 'Pull over and stop',
    't_schritt': 'Walking pace',
    't_30': 'Speed limit 30',
    't_zone30': '30 zone',
    't_50': 'Speed limit 50',
    't_70': 'Speed limit 70',
    't_100': 'Speed limit 100',
    't_frei': 'End of speed limit',
    // Hinweise
    'reihenfolge': 'Indicator, rear-view mirror, side mirror, shoulder check',
    'spiegel': 'Mirrors',
    'blinker': 'Indicator',
    'schulterblick': 'Shoulder check',
    'rundumblick': 'Look all around',
    'nach_hinten': 'Look behind you',
    'vorfahrt_gewaehren': 'Give way',
    'vorfahrtstrasse': 'Priority road',
    'hindernis': 'Obstacle',
    'abstand': 'Keep your distance',
    'gang': 'Change gear',
    'anhalten': 'Stop the car',
    'stopp': 'Stop',
    // Grundfahraufgaben
    'gfa_laengs': 'Parallel park in reverse',
    'gfa_quer_vor': 'Bay park forwards',
    'gfa_quer_rueck': 'Bay park in reverse',
    'gfa_bremsung': 'Emergency stop',
    'gfa_ecke': 'Reverse around the corner to the right',
    'gfa_umkehren': 'Turn the car around',
    // Rückmeldung
    'lob': 'Well done',
    'perfekt': 'Perfect!',
    'fehler': 'Not good',
    // Abfahrtkontrolle
    'tuev': 'Inspection sticker',
    'bremse': 'Brakes',
    'hupe': 'Horn',
    'scheibenwischer': 'Windscreen wipers',
    'warndreieck': 'Warning triangle',
    'warnweste': 'High-visibility vest',
    'verbandskasten': 'First aid kit',
    // Beleuchtung
    'abblendlicht': 'Dipped headlights',
    'fernlicht': 'Full beam',
    'standlicht': 'Sidelights',
    'blinker_fz': 'Indicators',
    'warnblinker': 'Hazard lights',
    'bremslicht': 'Brake lights',
    'ruecklicht': 'Rear lights',
    'nebel': 'Fog lights',
    'kennzeichenlicht': 'Number plate light',
    // Reifen
    'profil': 'Tread depth',
    'reifendruck': 'Tyre pressure',
    'reifenzustand': 'Tyre condition',
    'felgen': 'Wheel rims',
    // Flüssigkeiten
    'motoroel': 'Engine oil',
    'kuehlwasser': 'Coolant',
    'bremsfluessigkeit': 'Brake fluid',
    'wischwasser': 'Screen wash',
    // Assistenz
    'abs': 'ABS',
    'esp': 'ESP',
    'spurhalte': 'Lane keeping assist',
    'notbrems': 'Emergency brake assist',
    'acc': 'Adaptive cruise control',
    'totwinkel': 'Blind spot assist',
    'parkassistent': 'Parking assist',
    'tempomat': 'Cruise control',
    // Einweisung
    'sitz': 'Adjust your seat',
    'innenspiegel': 'Rear-view mirror',
    'aussenspiegel_l': 'Left side mirror',
    'aussenspiegel_r': 'Right side mirror',
    'gurt': 'Fasten your seatbelt',
    'lenkrad': 'Steering wheel',
    'zuendung': 'Ignition',
    'kupplung': 'Clutch',
    'handbremse': 'Handbrake',
    'schaltung': 'Gear stick',
    // Coaching
    'ruhig': 'Stay calm',
    'konzentration': 'Concentrate',
    'durchatmen': 'Take a deep breath',
    'locker': 'Relax',
    'vertrauen': 'Trust yourself',
    'nicht_eilig': 'Take your time',
    // Organisation
    'pause': 'Take a break',
    'tanken': 'Refuel',
    'platztausch': 'Swap seats',
    'zur_fahrschule': 'Back to the driving school',
    'trinken': 'Drink break',
    'gleich_fertig': 'Almost done',
  },
  VoiceLanguage.tr: {
    'links': 'Sol',
    'rechts': 'Sağ',
    'geradeaus': 'Düz devam',
    'abbiegen_links': 'Sola dön',
    'abbiegen_rechts': 'Sağa dön',
    'einordnen_links': 'Sol şeride geç',
    'einordnen': 'Şeride geç',
    'einordnen_rechts': 'Sağ şeride geç',
    'kreisverkehr': 'Döner kavşak',
    'ampel': 'Trafik lambası',
    'ausfahrt1': 'Birinci çıkış',
    'ausfahrt2': 'İkinci çıkış',
    'ausfahrt3': 'Üçüncü çıkış',
    'folgen': 'Yolu takip et',
    'rueckwaerts': 'Geri git',
    'langsamer': 'Yavaşla',
    'schneller': 'Hızlan',
    'bremsen': 'Fren yap',
    'parken': 'Kenara çek ve dur',
    't_schritt': 'Yürüme hızı',
    't_30': 'Hız sınırı 30',
    't_zone30': '30 bölgesi',
    't_50': 'Hız sınırı 50',
    't_70': 'Hız sınırı 70',
    't_100': 'Hız sınırı 100',
    't_frei': 'Hız sınırı sonu',
    'reihenfolge': 'Sinyal, iç ayna, dış ayna, omuz kontrolü',
    'spiegel': 'Aynalar',
    'blinker': 'Sinyal',
    'schulterblick': 'Omuz kontrolü',
    'rundumblick': 'Etrafına bak',
    'nach_hinten': 'Arkaya bak',
    'vorfahrt_gewaehren': 'Yol ver',
    'vorfahrtstrasse': 'Ana yol',
    'hindernis': 'Engel',
    'abstand': 'Mesafeni koru',
    'gang': 'Vites değiştir',
    'anhalten': 'Aracı durdur',
    'stopp': 'Dur',
    'gfa_laengs': 'Geri geri paralel park',
    'gfa_quer_vor': 'İleri dik park',
    'gfa_quer_rueck': 'Geri geri dik park',
    'gfa_bremsung': 'Acil fren',
    'gfa_ecke': 'Geri geri sağa köşe dönüşü',
    'gfa_umkehren': 'Aracı geri çevir',
    'lob': 'Aferin',
    'perfekt': 'Mükemmel!',
    'fehler': 'İyi değil',
    'tuev': 'Muayene etiketi',
    'bremse': 'Fren',
    'hupe': 'Korna',
    'scheibenwischer': 'Silecekler',
    'warndreieck': 'İkaz üçgeni',
    'warnweste': 'Reflektörlü yelek',
    'verbandskasten': 'İlk yardım çantası',
    'abblendlicht': 'Kısa far',
    'fernlicht': 'Uzun far',
    'standlicht': 'Park lambası',
    'blinker_fz': 'Sinyal lambaları',
    'warnblinker': 'Dörtlü flaşör',
    'bremslicht': 'Fren lambası',
    'ruecklicht': 'Arka lamba',
    'nebel': 'Sis farı',
    'kennzeichenlicht': 'Plaka lambası',
    'profil': 'Diş derinliği',
    'reifendruck': 'Lastik basıncı',
    'reifenzustand': 'Lastik durumu',
    'felgen': 'Jantlar',
    'motoroel': 'Motor yağı',
    'kuehlwasser': 'Soğutma suyu',
    'bremsfluessigkeit': 'Fren hidroliği',
    'wischwasser': 'Cam suyu',
    'abs': 'ABS',
    'esp': 'ESP',
    'spurhalte': 'Şerit takip asistanı',
    'notbrems': 'Acil fren asistanı',
    'acc': 'Adaptif hız sabitleyici',
    'totwinkel': 'Kör nokta asistanı',
    'parkassistent': 'Park asistanı',
    'tempomat': 'Hız sabitleyici',
    'sitz': 'Koltuğu ayarla',
    'innenspiegel': 'İç ayna',
    'aussenspiegel_l': 'Sol dış ayna',
    'aussenspiegel_r': 'Sağ dış ayna',
    'gurt': 'Emniyet kemerini tak',
    'lenkrad': 'Direksiyon',
    'zuendung': 'Kontak',
    'kupplung': 'Debriyaj',
    'handbremse': 'El freni',
    'schaltung': 'Vites kolu',
    'ruhig': 'Sakin ol',
    'konzentration': 'Konsantre ol',
    'durchatmen': 'Derin nefes al',
    'locker': 'Rahatla',
    'vertrauen': 'Kendine güven',
    'nicht_eilig': 'Acele etme',
    'pause': 'Mola ver',
    'tanken': 'Yakıt al',
    'platztausch': 'Yer değiştirin',
    'zur_fahrschule': 'Sürücü kursuna dönüş',
    'trinken': 'Su molası',
    'gleich_fertig': 'Az kaldı',
  },
  VoiceLanguage.ar: {
    'links': 'يسار',
    'rechts': 'يمين',
    'geradeaus': 'إلى الأمام مباشرة',
    'abbiegen_links': 'انعطف يسارًا',
    'abbiegen_rechts': 'انعطف يمينًا',
    'einordnen_links': 'التزم المسار الأيسر',
    'einordnen': 'التزم المسار',
    'einordnen_rechts': 'التزم المسار الأيمن',
    'kreisverkehr': 'دوّار',
    'ampel': 'إشارة المرور',
    'ausfahrt1': 'المخرج الأول',
    'ausfahrt2': 'المخرج الثاني',
    'ausfahrt3': 'المخرج الثالث',
    'folgen': 'تابع الطريق',
    'rueckwaerts': 'إلى الخلف',
    'langsamer': 'خفّف السرعة',
    'schneller': 'زد السرعة',
    'bremsen': 'اضغط الفرامل',
    'parken': 'توقّف على جانب الطريق',
    't_schritt': 'سرعة المشي',
    't_30': 'السرعة القصوى 30',
    't_zone30': 'منطقة 30',
    't_50': 'السرعة القصوى 50',
    't_70': 'السرعة القصوى 70',
    't_100': 'السرعة القصوى 100',
    't_frei': 'نهاية تحديد السرعة',
    'reihenfolge': 'الإشارة، المرآة الداخلية، المرآة الجانبية، النظر فوق الكتف',
    'spiegel': 'المرايا',
    'blinker': 'الإشارة',
    'schulterblick': 'انظر فوق كتفك',
    'rundumblick': 'انظر حولك',
    'nach_hinten': 'انظر إلى الخلف',
    'vorfahrt_gewaehren': 'أعطِ الأولوية',
    'vorfahrtstrasse': 'طريق ذو أولوية',
    'hindernis': 'عائق',
    'abstand': 'حافظ على المسافة',
    'gang': 'غيّر السرعة',
    'anhalten': 'أوقف السيارة',
    'stopp': 'قف',
    'gfa_laengs': 'اصطفاف موازٍ إلى الخلف',
    'gfa_quer_vor': 'اصطفاف عمودي إلى الأمام',
    'gfa_quer_rueck': 'اصطفاف عمودي إلى الخلف',
    'gfa_bremsung': 'فرملة طارئة',
    'gfa_ecke': 'الرجوع حول الزاوية يمينًا',
    'gfa_umkehren': 'اعكس اتجاه السيارة',
    'lob': 'أحسنت',
    'perfekt': 'ممتاز!',
    'fehler': 'ليس جيدًا',
    'tuev': 'ملصق الفحص الفني',
    'bremse': 'الفرامل',
    'hupe': 'البوق',
    'scheibenwischer': 'مسّاحات الزجاج',
    'warndreieck': 'مثلث التحذير',
    'warnweste': 'السترة العاكسة',
    'verbandskasten': 'حقيبة الإسعافات الأولية',
    'abblendlicht': 'الضوء المنخفض',
    'fernlicht': 'الضوء العالي',
    'standlicht': 'أضواء الوقوف',
    'blinker_fz': 'أضواء الإشارة',
    'warnblinker': 'أضواء التحذير',
    'bremslicht': 'ضوء الفرامل',
    'ruecklicht': 'الضوء الخلفي',
    'nebel': 'أضواء الضباب',
    'kennzeichenlicht': 'ضوء لوحة الأرقام',
    'profil': 'عمق نقشة الإطار',
    'reifendruck': 'ضغط الإطارات',
    'reifenzustand': 'حالة الإطارات',
    'felgen': 'الجنوط',
    'motoroel': 'زيت المحرك',
    'kuehlwasser': 'سائل التبريد',
    'bremsfluessigkeit': 'سائل الفرامل',
    'wischwasser': 'ماء غسيل الزجاج',
    'abs': 'ABS',
    'esp': 'ESP',
    'spurhalte': 'مساعد الحفاظ على المسار',
    'notbrems': 'مساعد الفرملة الطارئة',
    'acc': 'مثبّت السرعة التكيفي',
    'totwinkel': 'مساعد النقطة العمياء',
    'parkassistent': 'مساعد الركن',
    'tempomat': 'مثبّت السرعة',
    'sitz': 'اضبط المقعد',
    'innenspiegel': 'المرآة الداخلية',
    'aussenspiegel_l': 'المرآة الجانبية اليسرى',
    'aussenspiegel_r': 'المرآة الجانبية اليمنى',
    'gurt': 'اربط حزام الأمان',
    'lenkrad': 'عجلة القيادة',
    'zuendung': 'مفتاح التشغيل',
    'kupplung': 'دواسة القابض',
    'handbremse': 'فرامل اليد',
    'schaltung': 'ذراع ناقل الحركة',
    'ruhig': 'ابقَ هادئًا',
    'konzentration': 'ركّز',
    'durchatmen': 'خذ نفسًا عميقًا',
    'locker': 'استرخِ',
    'vertrauen': 'ثق بنفسك',
    'nicht_eilig': 'لا تستعجل',
    'pause': 'خذ استراحة',
    'tanken': 'تزوّد بالوقود',
    'platztausch': 'تبادلا المقاعد',
    'zur_fahrschule': 'العودة إلى مدرسة القيادة',
    'trinken': 'استراحة للشرب',
    'gleich_fertig': 'أوشكنا على الانتهاء',
  },
  VoiceLanguage.uk: {
    'links': 'Ліворуч',
    'rechts': 'Праворуч',
    'geradeaus': 'Прямо',
    'abbiegen_links': 'Поверни ліворуч',
    'abbiegen_rechts': 'Поверни праворуч',
    'einordnen_links': 'Займи лівий ряд',
    'einordnen': 'Займи ряд',
    'einordnen_rechts': 'Займи правий ряд',
    'kreisverkehr': 'Кільцевий рух',
    'ampel': 'Світлофор',
    'ausfahrt1': 'Перший з’їзд',
    'ausfahrt2': 'Другий з’їзд',
    'ausfahrt3': 'Третій з’їзд',
    'folgen': 'Їдь далі дорогою',
    'rueckwaerts': 'Заднім ходом',
    'langsamer': 'Повільніше',
    'schneller': 'Швидше',
    'bremsen': 'Гальмуй',
    'parken': 'Зупинись біля узбіччя',
    't_schritt': 'Швидкість пішохода',
    't_30': 'Обмеження 30',
    't_zone30': 'Зона 30',
    't_50': 'Обмеження 50',
    't_70': 'Обмеження 70',
    't_100': 'Обмеження 100',
    't_frei': 'Кінець обмеження швидкості',
    'reihenfolge':
        'Поворотник, внутрішнє дзеркало, бокове дзеркало, погляд через плече',
    'spiegel': 'Дзеркала',
    'blinker': 'Поворотник',
    'schulterblick': 'Поглянь через плече',
    'rundumblick': 'Озирнись навколо',
    'nach_hinten': 'Поглянь назад',
    'vorfahrt_gewaehren': 'Дай дорогу',
    'vorfahrtstrasse': 'Головна дорога',
    'hindernis': 'Перешкода',
    'abstand': 'Тримай дистанцію',
    'gang': 'Зміни передачу',
    'anhalten': 'Зупинись',
    'stopp': 'Стоп',
    'gfa_laengs': 'Паралельне паркування заднім ходом',
    'gfa_quer_vor': 'Перпендикулярне паркування передом',
    'gfa_quer_rueck': 'Перпендикулярне паркування заднім ходом',
    'gfa_bremsung': 'Екстрене гальмування',
    'gfa_ecke': 'Заднім ходом за ріг праворуч',
    'gfa_umkehren': 'Розверни автомобіль',
    'lob': 'Молодець',
    'perfekt': 'Чудово!',
    'fehler': 'Не добре',
    'tuev': 'Наклейка техогляду',
    'bremse': 'Гальма',
    'hupe': 'Звуковий сигнал',
    'scheibenwischer': 'Склоочисники',
    'warndreieck': 'Знак аварійної зупинки',
    'warnweste': 'Світловідбивний жилет',
    'verbandskasten': 'Аптечка',
    'abblendlicht': 'Ближнє світло',
    'fernlicht': 'Дальнє світло',
    'standlicht': 'Габаритні вогні',
    'blinker_fz': 'Покажчики повороту',
    'warnblinker': 'Аварійна сигналізація',
    'bremslicht': 'Стоп-сигнал',
    'ruecklicht': 'Задні ліхтарі',
    'nebel': 'Протитуманні фари',
    'kennzeichenlicht': 'Підсвічування номерного знака',
    'profil': 'Глибина протектора',
    'reifendruck': 'Тиск у шинах',
    'reifenzustand': 'Стан шин',
    'felgen': 'Колісні диски',
    'motoroel': 'Моторна олива',
    'kuehlwasser': 'Охолоджувальна рідина',
    'bremsfluessigkeit': 'Гальмівна рідина',
    'wischwasser': 'Рідина склоомивача',
    'abs': 'ABS',
    'esp': 'ESP',
    'spurhalte': 'Асистент утримання смуги',
    'notbrems': 'Асистент екстреного гальмування',
    'acc': 'Адаптивний круїз-контроль',
    'totwinkel': 'Асистент сліпих зон',
    'parkassistent': 'Асистент паркування',
    'tempomat': 'Круїз-контроль',
    'sitz': 'Налаштуй сидіння',
    'innenspiegel': 'Внутрішнє дзеркало',
    'aussenspiegel_l': 'Ліве бокове дзеркало',
    'aussenspiegel_r': 'Праве бокове дзеркало',
    'gurt': 'Пристебнися',
    'lenkrad': 'Кермо',
    'zuendung': 'Запалювання',
    'kupplung': 'Зчеплення',
    'handbremse': 'Ручне гальмо',
    'schaltung': 'Важіль перемикання передач',
    'ruhig': 'Спокійно',
    'konzentration': 'Зосередься',
    'durchatmen': 'Глибоко вдихни',
    'locker': 'Розслабся',
    'vertrauen': 'Вір у себе',
    'nicht_eilig': 'Не поспішай',
    'pause': 'Зроби перерву',
    'tanken': 'Заправка',
    'platztausch': 'Помінятися місцями',
    'zur_fahrschule': 'Назад до автошколи',
    'trinken': 'Перерва, щоб попити',
    'gleich_fertig': 'Майже закінчили',
  },
  VoiceLanguage.ru: {
    'links': 'Налево',
    'rechts': 'Направо',
    'geradeaus': 'Прямо',
    'abbiegen_links': 'Поверни налево',
    'abbiegen_rechts': 'Поверни направо',
    'einordnen_links': 'Займи левый ряд',
    'einordnen': 'Займи ряд',
    'einordnen_rechts': 'Займи правый ряд',
    'kreisverkehr': 'Круговое движение',
    'ampel': 'Светофор',
    'ausfahrt1': 'Первый съезд',
    'ausfahrt2': 'Второй съезд',
    'ausfahrt3': 'Третий съезд',
    'folgen': 'Следуй по дороге',
    'rueckwaerts': 'Задним ходом',
    'langsamer': 'Медленнее',
    'schneller': 'Быстрее',
    'bremsen': 'Тормози',
    'parken': 'Остановись у обочины',
    't_schritt': 'Скорость пешехода',
    't_30': 'Ограничение 30',
    't_zone30': 'Зона 30',
    't_50': 'Ограничение 50',
    't_70': 'Ограничение 70',
    't_100': 'Ограничение 100',
    't_frei': 'Конец ограничения скорости',
    'reihenfolge':
        'Поворотник, салонное зеркало, боковое зеркало, взгляд через плечо',
    'spiegel': 'Зеркала',
    'blinker': 'Поворотник',
    'schulterblick': 'Посмотри через плечо',
    'rundumblick': 'Осмотрись вокруг',
    'nach_hinten': 'Посмотри назад',
    'vorfahrt_gewaehren': 'Уступи дорогу',
    'vorfahrtstrasse': 'Главная дорога',
    'hindernis': 'Препятствие',
    'abstand': 'Держи дистанцию',
    'gang': 'Переключи передачу',
    'anhalten': 'Остановись',
    'stopp': 'Стоп',
    'gfa_laengs': 'Параллельная парковка задним ходом',
    'gfa_quer_vor': 'Перпендикулярная парковка передом',
    'gfa_quer_rueck': 'Перпендикулярная парковка задним ходом',
    'gfa_bremsung': 'Экстренное торможение',
    'gfa_ecke': 'Задним ходом за угол направо',
    'gfa_umkehren': 'Разверни машину',
    'lob': 'Молодец',
    'perfekt': 'Отлично!',
    'fehler': 'Нехорошо',
    'tuev': 'Наклейка техосмотра',
    'bremse': 'Тормоза',
    'hupe': 'Звуковой сигнал',
    'scheibenwischer': 'Дворники',
    'warndreieck': 'Знак аварийной остановки',
    'warnweste': 'Светоотражающий жилет',
    'verbandskasten': 'Аптечка',
    'abblendlicht': 'Ближний свет',
    'fernlicht': 'Дальний свет',
    'standlicht': 'Габаритные огни',
    'blinker_fz': 'Указатели поворота',
    'warnblinker': 'Аварийная сигнализация',
    'bremslicht': 'Стоп-сигнал',
    'ruecklicht': 'Задние фонари',
    'nebel': 'Противотуманные фары',
    'kennzeichenlicht': 'Подсветка номерного знака',
    'profil': 'Глубина протектора',
    'reifendruck': 'Давление в шинах',
    'reifenzustand': 'Состояние шин',
    'felgen': 'Колёсные диски',
    'motoroel': 'Моторное масло',
    'kuehlwasser': 'Охлаждающая жидкость',
    'bremsfluessigkeit': 'Тормозная жидкость',
    'wischwasser': 'Жидкость омывателя',
    'abs': 'ABS',
    'esp': 'ESP',
    'spurhalte': 'Система удержания в полосе',
    'notbrems': 'Система экстренного торможения',
    'acc': 'Адаптивный круиз-контроль',
    'totwinkel': 'Контроль слепых зон',
    'parkassistent': 'Парковочный ассистент',
    'tempomat': 'Круиз-контроль',
    'sitz': 'Настрой сиденье',
    'innenspiegel': 'Салонное зеркало',
    'aussenspiegel_l': 'Левое боковое зеркало',
    'aussenspiegel_r': 'Правое боковое зеркало',
    'gurt': 'Пристегнись',
    'lenkrad': 'Руль',
    'zuendung': 'Зажигание',
    'kupplung': 'Сцепление',
    'handbremse': 'Ручной тормоз',
    'schaltung': 'Рычаг переключения передач',
    'ruhig': 'Спокойно',
    'konzentration': 'Сосредоточься',
    'durchatmen': 'Глубоко вдохни',
    'locker': 'Расслабься',
    'vertrauen': 'Верь в себя',
    'nicht_eilig': 'Не торопись',
    'pause': 'Сделай перерыв',
    'tanken': 'Заправка',
    'platztausch': 'Поменяться местами',
    'zur_fahrschule': 'Обратно в автошколу',
    'trinken': 'Перерыв, чтобы попить',
    'gleich_fertig': 'Почти закончили',
  },
};
